version: "3"

services:
  web02:
    container_name: patient-care-web02
    hostname: patient-care-web
    ports:
      - "9002:8080"
    build:
      context: ..
    env_file:
      - ../config/.env.dev
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - docker_network

networks: # 가장 기본적인 bridge 네트워크
  docker_network:
    driver: bridge
    external: true