# 파일 규격 버전
version: "3.1"

# 실행하려는 컨테이너들 정의
services:
  web01:
    container_name: ego-web
    hostname: ego-web
    ports:
      - "9001:8080"
    env_file:
      - ./denb-web/config/.env.dev
    build:
      context: ./ego-web/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - network

networks: # 가장 기본적인 bridge 네트워크
  network:
    driver: bridge
