# 파일 규격 버전
version: "3.1"

# 실행하려는 컨테이너들 정의
services:
  web:
    container_name: ego_web
    hostname: ego_web
    ports:
      - "9003:8080"
    env_file:
      - ./egov-web/config/.env.dev
    build:
      context: ./egov-web/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - network

networks: # 가장 기본적인 bridge 네트워크
  network:
    driver: bridge
